swagger: "2.0"
info:
  description: "A RESTful API server for creating and deleting TXT records in BIND DNS"
  version: "1.0.0"
  title: "BIND API"
  contact:
    email: "a+git@pxd.ch"
  license:
    name: "GPL"
    url: "https://www.gnu.org/licenses/gpl-3.0.en.html"
host: "127.0.0.1"
basePath: "/"
tags:
- name: "dns"
  description: "All DNS related functionality"
  externalDocs:
    description: "Git repo"
    url: "https://github.com/Klar/bind-restapi"
schemes:
- "https"
paths:
  /zones:
    get:
      tags:
        - "dns"
      summary: "GET bind zones"
      operationId: "get"
      produces:
        - "application/json"
      parameters:
        - in: header
          name: "X-Api-Key"
          type: string
          description: "The API key used to authorize the request"
          required: true
      responses:
        "200":
          description: "'named-checkconf -l' in JSON format"
  /zones/{zoneId}/records/{recordName}:
    post:
      tags:
        - "dns"
      summary: "Create new DNS record"
      operationId: "post"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: header
          name: "X-Api-Key"
          type: string
          description: "The API key used to authorize the request"
          required: true
        - name: zoneId
          in: path
          description: zoneId i.e example.com
          type: string
          required: true
        - name: recordName
          in: path
          description: recordName i.e test
          type: string
          required: true
        - in: body
          name: body
          description: "new txt entries"
          schema:
            type: object
            required:
              - type
              - ttl
              - values
            properties:
              type:
                type: string
                description: "Type which must always be TXT"
                enum: 
                  - TXT
                example: TXT
              ttl:
                type: integer
                description: "Overrides default TTL of all records created in this request with provided value"
                example: 60
              values:
                type: array
                description: "TXT values to insert for {recordName}"
                items:
                  type: string
                example: ["str1", "str2", "str3"]
      responses:
        "200":
          description: "Record created"
        "400":
          description: "We only allow TXT updates."
        "401":
          description: "X-Api-Key not correct"
        "500":
          description: "Unable to create record on nameserver..."
    delete:
      tags:
        - "dns"
      summary: "Delete DNS records TXT entries"
      operationId: "delete"
      produces:
        - "application/json"
      parameters:
        - in: header
          name: "X-Api-Key"
          type: string
          description: "The API key used to authorize the request"
          required: true
        - name: zoneId
          in: path
          description: zoneId i.e example.com
          type: string
          required: true
        - name: recordName
          in: path
          description: recordName i.e test
          type: string
          required: true
      responses:
        "200":
          description: "Record deleted"
        "400":
          description: "URL is not in correct format."
        "401":
          description: "X-Api-Key not correct"
        "500":
          description: "Unable to delete record using any of the provided nameservers..."
